export const CANVAS_W = 800;
export const CANVAS_H = 300;
export const GROUND_Y = 260;
export const INITIAL_SPEED = 300;       // pixels per second
export const SPRITE_SCALE = 0.35;
export const MAX_SPEED = 800;           // pixels per second
export const SPEED_INCREMENT = 30;     // pixels/second per second of acceleration
export const BG_PARALLAX = 0.3;        // background moves at 30% of ground speed
export const SCORE_RATE = 0.005;       // score points per pixel of distance
export const DINO_FRAME_DURATION = 100; // ms per animation frame
export const DINO_RUN_FRAME_COUNT = 3;  // number of run animation frames
export const BG_ELEMENT_COUNT = 5;     // number of background parallax elements
export const GROUND_DASH_CYCLE = 40;   // 2x dash(8) + gap(12) = 40px wrap cycle for ground line
export const DINO_JUMP_VY = -600;          // initial upward velocity, px/s
export const DINO_GRAVITY = 1800;          // downward accel, px/s²
export const DINO_FAST_FALL_GRAVITY = 3600; // fast-fall accel (↓ in air), px/s²
export const OBSTACLE_SPAWN_MIN = 1.0;    // seconds between obstacles (minimum)
export const OBSTACLE_SPAWN_MAX = 2.5;    // seconds between obstacles (maximum)
export const OBSTACLE_MIN_GAP = 300;      // px: minimum x-distance between last obstacle and spawn
export const CACTUS_HITBOX_SHRINK = 0.75; // hitbox is 75% of visual sprite dimensions
export const DINO_HITBOX_W = 95;       // dino run/jump collision width, px
export const DINO_HITBOX_H = 58;       // dino run/jump collision height, px
export const DINO_DUCK_HITBOX_W = 80;  // dino duck collision width, px
export const DINO_DUCK_HITBOX_H = 30;  // dino duck collision height, px
export const DOUBLE_CACTUS_SPACING = 0.9; // offset multiplier for double cactus pair
export const OBSTACLE_SPAWN_BUFFER = 50;  // px past CANVAS_W where obstacle spawns
export const OBSTACLE_SPAWN_RETRY = 0.1;  // seconds to wait before retrying blocked spawn
export const PTERO_SCORE_THRESHOLD = 200; // score before pterodactyls start spawning
export const PTERO_Y_HIGH = 160;          // high altitude: run under (bottom anchor px)
export const PTERO_Y_MID  = 210;          // head level: must duck (bottom anchor px)
export const PTERO_Y_LOW  = 240;          // low flight: must jump (bottom anchor px)
export const PTERO_FRAME_DURATION = 125;  // ms per wing-flap animation frame
export const PTERO_FRAME_COUNT = 3;       // number of pterodactyl animation frames
export const PTERO_HITBOX_SHRINK = 0.75;  // hitbox is 75% of frame 0 visual dimensions
